### ISSUE TITLE
Colony counts: 24 or 48 hour?

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/qualite-deau#11]
Bonjour

Les données de 2016 et 2017 ont des comptages à 24h et 48h. C'est également le cas pour les autres années. 

Pour les années 2016 et 2017, quels sont les comptages à utiliser lorsque les résultats sont comparés à ceux de 2020 - 2023 ?

Je vous remercie de votre réponse.

================== 

Hello

The data from 2016 and 2017 have counts at 24hours and 48hours. This is the case for the other years as well. 

For the years 2016 and 2017 which counts are we using when the results are being compared to 2020 - 2023?

Thank you

**Comment by rachelaronoff** [comment]
48h is our best count always for these analyses - we decided this early on.
thanks!

**Comment by hammerdirt-analyst** [comment]
Thank you
