### ISSUE TITLE
Rain data: 2023

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/qualite-deau#12]
Bonjour,

Nous n'avons pas le peluvemetrie pour 2023.

Les autres années ont été formatter avec https://github.com/hammerdirt-analyst/qualite-deau/commit/285c1993ef0853b3b5234537f333d1a0447e20f6

Merci

Hello,

We need the precipitation data for 2023.

The other years were formatted in commit https://github.com/hammerdirt-analyst/qualite-deau/commit/285c1993ef0853b3b5234537f333d1a0447e20f6

Thanks.

**Comment by rachelaronoff** [comment]
think this was passed on already, but will double check.

**Comment by rachelaronoff** [comment]
can close this, now, right? all good.

**Comment by hammerdirt-analyst** [comment]
Thank you for the rain data.
