### ISSUE TITLE
Data 2016: Only 24hour counts

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/qualite-deau#14]
Hello,

The data for 2016 does not include 48 hour counts. Can we please get a copy of the 2016 data with the 48hour counts?

thanks

**Comment by rachelaronoff** [comment]
All of the data is accessible via [this Zenodo repository](https://zenodo.org/record/5094576), including images of microbial colonies.  This [GitHub repo](https://github.com/Hackuarium/montreux-water-quality) and the [BES paper](https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1002/2688-8319.12094) calculate and present charts not only for the 2016, but also the 2017 data, based on 24h counts.  It was thus the lower limit averages reported for these published analyses. Halfway down[ this BES page is the info on the paper ](https://besjournals.onlinelibrary.wiley.com/hub/citizen_science_cfp)with the[ graphical abstract](https://jappliedecologyblog.files.wordpress.com/2021/10/infographic.png), which even provides an example of a plate after 24h vs 48h of incubation. (Longer incubation times give more clear results, as also found by other participatory research groups, i.e. waterwatch.)   Additionally, those initial data were also limited by having only three replicates for averages.  Guess this will be the opportunity to bring it all up to the level of the 48h counts.  (To note: the 2022 and 2023 data were done with 6 replicates, in the hopes that medians could also be analysed.)

**Comment by hammerdirt-analyst** [comment]
Hello,

Does this mean that we use the 24hour counts for 2016 and 2017?

Thank you

**Comment by rachelaronoff** [comment]
no, I think still we should use the 48h counts, and wonder if those charts labeled 24h just never changed their text, but actually are calculated on the 48h results.  we should be able to see in the code.  thanks

**Comment by hammerdirt-analyst** [comment]
Hello,

The data we have for 2016 is labeled 24 hour counts. Do you or do you not have the 2016 data with 48 hour counts? If you do please attach that data to the message. Unfortunately I am really busy at the moment, going through the previous repo and infering the status of the data from the code is time consuming and less reliable than simply getting the data from the person responsible.

Thanks

**Comment by rachelaronoff** [comment]
will do. have found more 48h data already from many weeks of the 2016 campaign, and also want to double check the image files.  thanks again.

**Comment by rachelaronoff** [comment]
The 2016 data, as is, must be what we use, as in the end only the last 4 weeks of that season's data included the 48h image files... (learning by doing - we remembered the WaterWatch recommendations?) =) thanks.

**Comment by rachelaronoff** [comment]
In other words: this 2016 file should be used, already in the repo: 2016_Data.csv
(but I can also pass on a long format csv with the 48h numbers and image names for half of the sampling weeks.)
Thank you.

**Comment by hammerdirt-analyst** [comment]
Thank you for confirming this.

We do not want to introduce any data unless it has a specic use. However this may come in handy later when we do the computer vsion script.
