### ISSUE TITLE
Data Standardization: Is Jazz?

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/qualite-deau#2]
Dans le cahier de normalisation des données, nous ne disposons pas d'une source de données pour les dates de début et de fin du festival pour chaque année d'échantillonnage.

Existe-t-il un enregistrement de ces dates ou devons-nous les rechercher ?

=== English Below===

In the data standardization notebook we do not have a data source for the start and end dates of the festival for each sampling year.

Did somebody keep a record of this?

**Comment by rachelaronoff** [comment]
Voici les dates de Jazz pour toutes les années de prélèvement :
2016 1er juillet-16 juillet
2017 30 juin-15 juillet
2020 Annulé en raison de la fermeture pour cause de pandémie (initialement prévu du 3 au 18 juillet)
2022 1-16 juillet
2023 30 juin-15 juillet

Here are the Jazz dates for all the sampling years:
2016 1July-16July
2017 30June-15July
2020 Cancelled with Pandemic lockdown (scheduled originally for 3-18July)
2022 1-16July
2023 30June-15July

**Comment by hammerdirt-analyst** [comment]
Hello,

Please use normal formatting and standard courtesy when addressing an issue. There is no need to bold your replies unless it is to emphasize a value.

thank you

**Comment by rachelaronoff** [comment]
Thanks for understanding:

Voici les dates de Jazz pour toutes les années de prélèvement :
2016 1-16 juillet
2017 30 juin-15 juillet
2020 Annulé en raison de la fermeture pour cause de pandémie (initialement prévu du 3 au 18 juillet)
2022 1-16 juillet
2023 30 juin-15 juillet

Here are the Jazz dates for all the sampling years:
2016 1-16 July
2017 30 June-15 July
2020 Cancelled with Pandemic lockdown (scheduled originally for 3-18 July)
2022 1-16 July
2023 30 June-15 July

**Comment by hammerdirt-analyst** [comment]
Thanks Rachel,

We will get this integrated tonight and see how it looks with the sample out put. We will leave this issue open to cover the display and labeling issues.

**Comment by hammerdirt-analyst** [comment]
see commit https://github.com/hammerdirt-analyst/qualite-deau/commit/876603467850e0b80a05798de66991b3e69bc301
