### ISSUE TITLE
Work in Progress - text issues 1-3 on page /data_standardization.html

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt-analyst/qualite-deau#3]
Proposed edits to the introductory text are put in **Bold**

(to note, my copy paste lost the original formatting, and initially I thought I should keep the original text in place, in italics, but it seemed too confusing to do this, so the bold simply defines the place were changes were made...)

Data processing
The water monitoring project  **around Montreux Bay** has been going on since 2016. The data has been collected and treated by a variety of people since then **as a participatory research project.**

Objective: Standardize the nomenclature from the different sampling years. Provide a model for storing and collecting data in the future.

Purpose: Define the probability that a survey will exceed a threshold value within the period of the year defined by the survey results.

Definitions

- **microbial plate or card: a solid support with media allowing growth of bacteria from inoculated water samples.**
- media/medium: **the provided nutrients and substrates of a microbial plate or card, which allow not only bacterial growth, but to distinguish bacterial species of each colony by color (or even fluorescence).  Components in media can also prevent many bacteria present in the water sample from growing (e.g. bile salts).**
- colony: a circular  **growth of individual bacteria from the inoculated water sample.** 
- colony-count: the number of colonies on a microbial plate or card.
- label: the assumed category of the observed colonies
        Bioindicator - **bacteria which indicate the presence of raw sewage in lake water, e.g. _Escherichia coli_ from the human gut.** 
        Coliform - **bacteria which are general indicators of water contamination, e.g.  _Enterobacter aerogenes_**
        Other - **bacteria which can grow on the given media, that are not part of the above categories, e.g. _Staphylococcus_, _Pseudomonas_**
- coef: the **correction factor applied, to allow reporting of ''colony counts per 100ml'' of the original water sample.  For instance, if 4ml was inoculated on a microbial plate, then the colony count would be multiplied by 25.**  

The purpose of the sampling is to **quantify** colonies and classify them **as belonging to one of the possible labelled categories**.

**Comment by rachelaronoff** [comment]
sorry, cannot find how to add the documentation label to this.
(maybe I miss a menu for this??)

**Comment by rachelaronoff** [comment]
the color changes for each colony are due to fermentation of substrates in the media.  different species of bacteria have different capacities to do this...

**Comment by hammerdirt-analyst** [comment]
This is not the correct method to propose changes.  You have addressed more than one section.

If  you want to replace text in the document use the the section number and put it in the form:

old text : proposed text
