### ISSUE TITLE
Work in progress, towards addressing further issues for the data standardization  

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt-analyst/qualite-deau#4]
For section 1.2 and 1.3 there are a couple of typos.

in 1.2
finished  
in 1.3
coefficient  (has both fs in section 1.2)
rainfall as one word (as used in the published article - https://besjournals.onlinelibrary.wiley.com/doi/10.1002/2688-8319.12094)

For section 1.4.1 about applying labels, in particular the Levine media colony color, purple, should be put as 'Coliform' colonies, and mauve should be put as 'Other' colonies. (At least one molecular validation result in the article showed a Mauve colony with a weak green sheen to be Pseudomonas.)  
Also, 'Double side ECC', 'Double side E coli' are both the same as, respectively, ECC-side or E-coli side  (so ultimately 'translated' as ECC or E coli).  
To note: these double-sided cards do not control for Aeromonas (like the newest ECC-A cards), and both overestimate the prevalence of their colony categories.  Additionally, all the colonies for 'E-coli side' show up as turquoise, so when people look at the original card images, they should avoid getting confused about this, somehow...

**Comment by hammerdirt-analyst** [comment]
For changes it is one section at a time. in the form section number:

old text:newtext
