### ISSUE TITLE
Title page extra

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt-analyst/qualite-deau#5]
For the title page here, here are a few possible changes:

Quantifying **bioindicator levels in lake water.**
This is a draft
authors: Rachel, Roger

**The community laboratory,** Hackuarium, has been monitoring **lake water quality over five summer seasons in Montreux Bay**, since 2016. This is a record of the results.

To note:
We want to have everything in French ultimately, but should avoid franglish...

**Comment by hammerdirt-analyst** [comment]
Hello,

I am sorry what does this have to do with the data standardization? I am sure that we will want to change the titlepage and many other texts. Right now we are only concerned with the out put of the data standardization module.

If we don not do this. There will be nothing to make a title page for.

We will close this issue. When we have a product to make a titlepage for we will discuss the titlepage.

Thank you
