### ISSUE TITLE
Coefficient 

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt-analyst/qualite-deau#8]
The definitions section could include more, as previously discussed.
For the moment, here is a suggestion of a better definition for the coefficient, which is used to correct for the amount of water put on the microbial plate or card (aka inoculation volume), so that the number of colonies per 100ml of original water sample is calculated.

Old text under definitions:
coef: the volume of water used for the sample

possible new text:
coefficient: the correction factor applied, to allow reporting of ''colony counts per 100ml'' of the original water sample. For instance, if 4ml was inoculated on a microbial plate, then the colony count would be multiplied by 25. Most microbial cards were inoculated with 1ml, so 100 is the coefficient used for quantification.

**Comment by hammerdirt-analyst** [comment]
Thanks Rachel,

maybe we will put only the definition for the data processing:

coefficient: the correction factor applied, to allow reporting of ''colony counts per 100ml'' of the original water sample.

This defines its purpose as a scaling factor and we need to be clear of its role for the math part. The rest of that text will be appropriate elsewhere, like in the caption of the first figure that uses the colony counts variable. Of it could be included as a formal definition at the begining of each yearly report. Along with all the other formal definitions and abbreviations that should accompany a report of this nature. We will make those decisions shortly

We will get the requested change in tonight

**Comment by hammerdirt-analyst** [comment]
see commit https://github.com/hammerdirt-analyst/qualite-deau/commit/876603467850e0b80a05798de66991b3e69bc301
