### ISSUE TITLE
Invalid count values for 2022 samples: "nd"

### ISSUE THREAD

**Issue by hammerdirt-analyst** [hammerdirt-analyst/qualite-deau#9]
Hello,

There are missing values for Vernex in 2022. See the results of the data processing module:

https://hammerdirt-analyst.github.io/qualite-deau/data_standardization.html

Do not attach the correct values to this issue. Send the data to analyst@hammerdirt.ch

If the rows can be excluded let us know here.

Thanks.

**Comment by rachelaronoff** [comment]
9 VNX samples from 18July!?  am I right?  will check.

**Comment by rachelaronoff** [comment]
Indeed, it was a mess up during inoculations - three cards were never inoculated with the sample replicates, so there are just 3 to use for that date and site.  These things happen (rarely).  Yes, they can be excluded.
Thank you.

**Comment by hammerdirt-analyst** [comment]
Thanks rachel

We will take care of this tonight and add the 2016/2017 data.
